### ISSUE TITLE
Could you upload the team picture please?

### ISSUE THREAD

**Issue by Johnson-Rachel** [jordanadrianoo/Drip-Drop#2]
please send the photo of all of us with our final presentation

**Comment by Johnson-Rachel** [comment]
Thanks

**Comment by jordanadrianoo** [comment]
Thank you all for your patience. [Team Pictures](https://github.com/jordanadrianoo/WaCode-Hackathon-Drip-Drop/tree/master/Team%20Pictures) is now available.
